openapi: 3.0.0
info:
  version: 1.0.0
  title: Hauth API
  license:
    name: The 3-Clause BSD License
servers:
- url: http://github.com/uclalibrary/hauth
paths:
  /access/{id}:
    get:
      summary: Get Supplied ID's access mode
      description: Whether the supplied ID's access mode is open, tiered, or all-or-nothing
      operationId: getAccessMode
      parameters:
        - in: path
          name: id
          description: The ID whose access mode we want to check
          schema:
            type: string
          required: true
      responses:
        '200':
          description: The information about the supplied ID's access mode
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessMode:
                    type: string
                    enum: [ OPEN, TIERED, ALL_OR_NOTHING ]
                    example: OPEN
        '404':
          description: Notification that the supplied ID couldn't be found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ NOT_FOUND ]
                    example: NOT_FOUND
                  message:
                    type: string
                    example: The requested ID was not found
        '500':
          description: There was an internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ INTERNAL ]
                    example: INTERNAL
                  message:
                    type: string
                    example: The service failed to connect to its database
  /cookie:
    get:
      summary: Get Authentication Cookie
      description: The authentication cookie service
      operationId: getCookie
      parameters:
      - in: query
        name: origin
        description: The origin of the page, consisting of a protocol, hostname and, optionally, port number
        schema:
          type: string
          format: uri
          example: https://client.example.com/
        required: true
      responses:
        '200':
          description: The cookie gets set in the response that includes Javascript to close the open tab/window
          headers:
            Set-Cookie:
              description: An encrypted cookie value that contains the supplied origin and access mode
              schema:
                type: string
                example: iiifauth=asrvaaDe43AAqw34QpOoPJR4j5b1; Path=/; HttpOnly
          content:
            text/html:
              schema:
                type: string
        '400':
          description: The request didn't contain an origin or contained one that wasn't valid
          content:
            text/html:
              schema:
                type: string
        '500':
          description: There was an internal server error
          content:
            text/html:
              schema:
                type: string
                example: The service failed to encrypt its cookie value
  /token:
    get:
      summary: Get Authentication Token
      description: The authentication token service
      operationId: getToken
      parameters:
      - in: cookie
        name: iiif-access
        schema:
          type: string
          example: iiif-access=asrvaaDe43AAqw34QpOoPJR4j5b1; Path=/; HttpOnly
        required: true
      - in: query
        name: origin
        description: The origin of the page, consisting of a protocol, hostname and, optionally, port number
        schema:
          type: string
          format: uri
          example: https://client.example.com/
        required: false
      - in: query
        name: messageId
        description: A string that both prompts the server to respond with a web page instead of JSON, and allows the client to match access token service requests with the messages received
        schema:
          type: string
          example: 1234
        required: false
      responses:
        '200':
          description: The access token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  expiresIn:
                    type: integer
            text/html:
              schema:
                type: string
                example: '<html><body><script>window.parent.postMessage({"messageId":"1234","accessToken":"TOKEN_HERE","expiresIn": 3600},"https://client.example.com/");</script></body></html>'
        '400':
          description: The request didn't contain a valid cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ INVALID_COOKIE ]
                    example: INVALID_COOKIE
                  message:
                    type: string
                    example: The request did not contain a valid cookie
        '500':
          description: There was an internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ CONFIGURATION ]
                    example: CONFIGURATION
                  message:
                    type: string
                    example: The access cookie decryption service is not configured properly
  /status:
    get:
      summary: Get Application Status
      description: Gets a response indicating the current status of the application. This may include information about
        the health of the server, details about which configuration options are engaged, and other things.
      operationId: getStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '500':
          description: There was an internal server error
