name: Maven PR Build

# We require all commits go through PR on GitHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      UCLALIBRARY_SNYK_ORG: ${{ secrets.UCLALIBRARY_SNYK_ORG }}
    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Check out code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@1d56b37995622db66cce1214d81014b09807fb5a # v4
        with:
          maven-version: 3.6.3
      - name: Build with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "clean verify"
          maven_profiles: default
          maven_args: >
            -V -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -Ddocker.showLogs=true
            -Dsnyk.skip=${{ secrets.SKIP_SNYK }}
      - name: Build with Maven, with optional environment variables set
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "clean verify"
          maven_profiles: default,optional-env-vars
          maven_args: >
            -V -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -Ddocker.showLogs=true
            -Dsnyk.skip=${{ secrets.SKIP_SNYK }}
